### ISSUE TITLE
2 errors on install

### ISSUE THREAD

**Issue by findmak** [oracle/oci-quickstart-cloudnative#20]
I get the following errors:
* oci_objectstorage_object_lifecycle_policy.mushop_deploy_assets_lifecycle_policy: 1 error occurred:
	* oci_objectstorage_object_lifecycle_policy.mushop_deploy_assets_lifecycle_policy: Service error:InsufficientServicePermissions. Permissions granted to the object storage service in this region are insufficient to execute this policy.. http status code: 400. Opc request id: lhr-0:g3hqouod8PcncAv0di+2SSPGdw40WQEajOM6KPkobB7YFC1tgIsKqDl1Nl/JWlC0

	* oci_core_instance.app-instance: 1 error occurred:
	* oci_core_instance.app-instance: Service error:NotAuthorizedOrNotFound. shape VM.Standard.E2.1.Micro not found. http status code: 404. Opc request id: d09f78a391159963e991dc196a5c1984/A9158EEC778BF1D526AEF7336BA23151/6126E87D2EEA8344569323D2965E54C5

If I re-run, I get the last error only: 
* oci_core_instance.app-instance: 1 error occurred:
	* oci_core_instance.app-instance: Service error:NotAuthorizedOrNotFound. shape VM.Standard.E2.1.Micro not found. http status code: 404. Opc request id: d09f78a391159963e991dc196a5c1984/A9158EEC778BF1D526AEF7336BA23151/6126E87D2EEA8344569323D2965E54C5

**Comment by mvandervliet** [comment]
@findmak - Thanks for reporting! These are known edge cases, and we are working to correct/document. The 2nd issue is due to the Micro compute availability in only one of the Availability Domains. Try editing the stack and choosing a different Availability Domain:

![image](https://user-images.githubusercontent.com/8783541/65158938-8c419f00-d9f0-11e9-8e67-a8e635c25d92.png)

**Comment by junior** [comment]
@findmak the Always Free resources are available on your home region and to one availability domain.

Which version are you using? Is the latest v1.0.2?

You can find your tenancy’s limits for Always Free resources in the Console. To check these limits: Open the navigation menu. Under Governance and Administration, go to Limits, Quotas and Usage. As documented here: https://docs.cloud.oracle.com/iaas/Content/FreeTier/freetier.htm

On the Limits, Quotas and Usage, you can select Compute, then select the Availability Domain (AD). The shape that you need is the VM.Standard.E2.1.micro. Check on which AD you have available resources.

**Comment by findmak** [comment]
Changing the availability domain worked, thanks :)

**Comment by jeevanjoseph** [comment]
Just summarizing for anyone else finding this thread and using `v1.0.2` :

- If you get issues around  `Service error:NotAuthorizedOrNotFound. shape VM.Standard.E2.1.Micro not found.`,  your Always Free eligible resources are in a different availability domain than what you selected when you selected when you deployed the application
Go to `Home > Governance > Limits, Quotas and Usage` to see where your `VM.Standard.E2.1.Micro` shapes are available.

- If you see `Service error:InsufficientServicePermissions. Permissions granted to the object storage service in this region are insufficient to execute this policy`: this is an edge case, and simply retrying the the `terrafrom apply` should resolve it.

We are working to address both issues.

**Comment by junior** [comment]
[FAQ](../blob/master/deploy/basic/FAQs.md) include detailing the possible issues and reference to the documentation.
