### ISSUE TITLE
Missing scripts

### ISSUE THREAD

**Issue by Jeevanhm** [oracle/oci-quickstart-cloudnative#27]
Apply failed with below errors.. 

Error: oci_objectstorage_object.entrypoint: 1 error occurred:
	* oci_objectstorage_object.entrypoint: file: open ./scripts/entrypoint.sh: no such file or directory in:
${file("./scripts/entrypoint.sh")}
Error: oci_objectstorage_object.apache_conf: 1 error occurred:
	* oci_objectstorage_object.apache_conf: file: open ./scripts/httpd.conf: no such file or directory in:
${file("./scripts/httpd.conf")}
Error: oci_objectstorage_object.mushop_basic: 1 error occurred:
	* oci_objectstorage_object.mushop_basic: file: open ./scripts/mushop-basic.tar.gz: no such file or directory in:
${file("./scripts/mushop-basic.tar.gz")}
Error: oci_objectstorage_object.catalogue_sql_script: 1 error occurred:
	* oci_objectstorage_object.catalogue_sql_script: file: open ./scripts/atp_mushop_catalogue.sql: no such file or directory in:
${file("./scripts/atp_mushop_catalogue.sql")}

**Comment by peterj** [comment]
Thanks for reporting this @Jeevanhm! We saw a similar issue #26   - can you provide additional information as mentioned in that issue?

**Comment by Jeevanhm** [comment]
I downloaded oci-quickstart-cloudnative-master.zip file and created RMS sucessfully. However when i click on plan or apply i get above error message.

**Comment by Jeevanhm** [comment]
well i downloaded the zip file from #26 which you posted and it worked perfectly fine. The issue is with oracle provided oci-quickstart-cloudnative-master.zip. It would be great if you can fix the mushop-basic-stack-v1.0.2.zip link from the main README.md

**Comment by junior** [comment]
@Jeevanhm the button <img width="147" alt="github_clone_download_button" src="https://user-images.githubusercontent.com/551007/65643018-3f446680-dfb6-11e9-8ec2-878403139c9f.png"> is a standard GitHub button to clone or download the entire repository. This does not download the release stack. We cannot change that button.

If you are cloning the repo, you can generate your own stack following these build [instructions](https://github.com/oracle/oci-quickstart-cloudnative/blob/master/deploy/basic/README.md).

On the main [README.md](https://github.com/oracle/oci-quickstart-cloudnative/blob/master/README.md), under the "Getting Started", the step 1, has the direct link for the pre-built stack release.

<img width="991" alt="main_README_stack_link" src="https://user-images.githubusercontent.com/551007/65643319-12448380-dfb7-11e9-80c3-1fc1926157bb.png">
